language: python
sudo: false
python:
- '2.7'
- '3.4'
env:
- DJANGO_VERSION_NUMBER=1.8
install:
- pip install codecov
- pip install django==$DJANGO_VERSION_NUMBER
- pip install -r requirements.txt
script:
- ./runtests-ci.sh
after_success:
- codecov

